### ISSUE TITLE
AutoMoli not working anymore .. nothing in logs

### ISSUE THREAD

**Issue by thundergreen** [benleb/ad-automoli#47]
Hello I used AutoMoli and was fan until today :P Well my setup stopped working. I changed the config to latest information in the release notes but still nothing work no error thrown. 

Here is my config maybe you can have a quick look:

```
entrance:
  module: automoli
  class: AutoMoLi
  room: Entrance
  disable_switch_entities: 
    - input_boolean.automoli_general
  delay: 10
  daytimes:
    - { starttime: "05:30", name: morning, light: 0 }
    - { starttime: "07:20", name: day, light: 1 }
    - { starttime: "20:30", name: evening, light: 1 }
    - { starttime: "22:30", name: night, light: 0 }
    - { starttime: "23:30", name: more_night, light: 0 }
  illuminance_threshold: 29
  illuminance: 
    - sensor.average_luminance_in_the_house
  lights:
    - light.entrance
  motion:
    - binary_sensor.multisenor_entrance_motion
  motion_state_on: "on"
  motion_state_off: "off"
```

all entities are there and work correctly Any hint here?

**Comment by benleb** [comment]
Hey, "nothing" means "absolutely nothing"? :) So no message about the parsed config or anything else from automoli - after the message of appdaemon that it loaded the app? Maybe something with `motion_state_*` - that's a feature I do not use myself and therefore gets even less testing ;D I will take a deeper look tomorrow :)

**Comment by thundergreen** [comment]
hey thanks for the info.. maybe this is a proble,:

```
        # stay compatible to the old setting
        if disable_switch_entity := self.args.get("disable_switch_entity"):
            self.disable_switch_entities.add(disable_switch_entity)
```
When I turn off input boolean I sucessfully get: 

```

2020-08-06 00:38:02.013889 INFO entrance:  AutoMoLi disabled by input_boolean.automoli_general

```

but if I turn it on no light automation is started :(


I also got this after reloading the app.

```

2020-08-06 00:33:51.612281 WARNING AppDaemon: Excessive time spent in utility loop: 4197.0ms, 4196.0ms in check_app_updates(), 1.0ms in other


```

**Comment by thundergreen** [comment]
```
2020-08-06 00:47:20.463077 INFO AppDaemon: Reading config


2020-08-06 00:47:20.729154 INFO AppDaemon: /config/appdaemon/apps/automoli.yaml added or modified


2020-08-06 00:47:20.729854 INFO AppDaemon: App 'entrance' changed


2020-08-06 00:47:20.730619 INFO AppDaemon: Found 7 total apps


2020-08-06 00:47:20.751465 INFO AppDaemon: Terminating entrance


2020-08-06 00:47:20.756656 INFO AppDaemon: Initializing app entrance using class AutoMoLi from module automoli


2020-08-06 00:47:23.713163 INFO entrance:  


2020-08-06 00:47:23.719188 INFO entrance: 💡 AutoMoLi - Entrance


2020-08-06 00:47:23.722716 INFO entrance:  


2020-08-06 00:47:23.728008 INFO entrance:   room: Entrance


2020-08-06 00:47:23.732544 INFO entrance:   disable_switch_entities:


2020-08-06 00:47:23.737509 INFO entrance:     - input_boolean.automoli_general


2020-08-06 00:47:23.742673 INFO entrance:   delay: 0:10min ≈ 10sec


2020-08-06 00:47:23.745644 INFO entrance:   daytimes:


2020-08-06 00:47:23.748682 INFO entrance:     morning:


2020-08-06 00:47:23.751917 INFO entrance:       starttime: 05:30


2020-08-06 00:47:23.754996 INFO entrance:       light: 0


2020-08-06 00:47:23.758845 INFO entrance:     day:


2020-08-06 00:47:23.764883 INFO entrance:       starttime: 07:20


2020-08-06 00:47:23.768134 INFO entrance:       light: 1


2020-08-06 00:47:23.773108 INFO entrance:     evening:


2020-08-06 00:47:23.776456 INFO entrance:       starttime: 20:30


2020-08-06 00:47:23.779625 INFO entrance:       light: 1


2020-08-06 00:47:23.788370 INFO entrance:     night:


2020-08-06 00:47:23.793102 INFO entrance:       starttime: 22:30


2020-08-06 00:47:23.797007 INFO entrance:       light: 1


2020-08-06 00:47:23.800633 INFO entrance:     more_night:


2020-08-06 00:47:23.804374 INFO entrance:       starttime: 23:30


2020-08-06 00:47:23.807723 INFO entrance:       light: 0


2020-08-06 00:47:23.810770 INFO entrance:   illuminance_threshold: 29


2020-08-06 00:47:23.813826 INFO entrance:   illuminance:


2020-08-06 00:47:23.816742 INFO entrance:     - sensor.average_luminance_in_the_house


2020-08-06 00:47:23.819725 INFO entrance:   lights:


2020-08-06 00:47:23.822664 INFO entrance:     - light.entrance


2020-08-06 00:47:23.826840 INFO entrance:   motion:


2020-08-06 00:47:23.829865 INFO entrance:     - binary_sensor.multisenor_entrance_motion


2020-08-06 00:47:23.832914 INFO entrance:   motion_state_on: on


2020-08-06 00:47:23.837844 INFO entrance:   motion_state_off: off


2020-08-06 00:47:23.843308 INFO entrance:   active_daytime: more_night


2020-08-06 00:47:23.846769 INFO entrance:   sensors:


2020-08-06 00:47:23.850356 INFO entrance:     motion:


2020-08-06 00:47:23.854373 INFO entrance:       - binary_sensor.multisenor_entrance_motion


2020-08-06 00:47:23.858401 INFO entrance:     illuminance:


2020-08-06 00:47:23.864320 INFO entrance:       - sensor.average_luminance_in_the_house


2020-08-06 00:47:23.868946 INFO entrance:  


2020-08-06 00:47:23.874537 WARNING AppDaemon: Excessive time spent in utility loop: 3417.0ms, 3414.0ms in check_app_updates(), 3.0ms in other

```

**Comment by benleb** [comment]
@thundergreen if you want, you can try the master now... May be it is fixed - if not, what gets logged now? :D

**Comment by thundergreen** [comment]
Nope did not fix it :( THe thing is .. nothing in logs.. It just won't react to motion. That's weird as it worked very well before.. dunno what happened:(

**Comment by benleb** [comment]
Oh sorry.. but now I got it 😎  I promise ✌️ 😄  Push & release tomorrow, good night!

**Comment by Gibby** [comment]
I had to downgrade to 0.7.2 to get mine working again.

**Comment by benleb** [comment]
@thundergreen & @Gibby could you please test the master? If confirmed working, I will do a release :)
https://github.com/benleb/ad-automoli/commit/d6774972ddc2b84781db2bfd5a9d87792cfe5e93 should finally fix this, the missing `await` [here](https://github.com/benleb/ad-automoli/blob/d6774972ddc2b84781db2bfd5a9d87792cfe5e93/apps/automoli/automoli.py#L279) was the root cause 🙄 sorry!

**Comment by thundergreen** [comment]
@benleb I'll test and report.. I just started entity controller but that's too odd for my needs. Hope it'll work :)

**Comment by thundergreen** [comment]
> @thundergreen & @Gibby could you please test the master? If confirmed working, I will do a release :)
> [d677497](https://github.com/benleb/ad-automoli/commit/d6774972ddc2b84781db2bfd5a9d87792cfe5e93) should finally fix this, the missing `await` [here](https://github.com/benleb/ad-automoli/blob/d6774972ddc2b84781db2bfd5a9d87792cfe5e93/apps/automoli/automoli.py#L279) was the root cause 🙄 sorry!

I'll test and report asap. Thanks a lot my friend!

**Comment by thundergreen** [comment]
Confirmed. Works again. You can release. I'll test it an reoirt if there are any issue.. Thanks 100 times u saved me hundreds of hours work and troubles with my wife :P

**Comment by benleb** [comment]
Ah I see... I also live with my girlfriend and know exactly what you mean :D

Thanks!
